<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <InvariantGlobalization>false</InvariantGlobalization>
        <WarningsNotAsErrors>NU1900</WarningsNotAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.1" />
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    </ItemGroup>

</Project>
